name: cascam
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python>=3.8
  
  # Core deep learning (PyTorch ecosystem)
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=12.1  # For CUDA support, adjust version as needed
  
  # Scientific computing & visualization
  - numpy>=1.21.0
  - matplotlib>=3.5.0
  - pillow>=8.0.0
  
  # Configuration & utilities
  - pyyaml>=6.0.0
  
  # Python packages via pip
  - pip
  - pip:
    - fastai>=2.7.0
    - grad-cam>=1.4.0
  
  # Development tools (optional)
  - jupyter
  - jupyterlab
  - ipywidgets
  
  # Code quality tools
  - black
  - isort
  - flake8
  - pytest
  - pytest-cov

# Alternative CPU-only environment (uncomment if GPU not available)
# name: cascam-cpu
# channels:
#   - pytorch
#   - conda-forge
#   - defaults
# 
# dependencies:
#   - python>=3.8
#   - pytorch-cpu>=2.0.0
#   - torchvision-cpu>=0.15.0
#   - numpy>=1.21.0
#   - matplotlib>=3.5.0
#   - pillow>=8.0.0
#   - tqdm>=4.60.0
#   - jupyter
#   - jupyterlab
#   - ipywidgets
#   - seaborn
#   - black
#   - isort
#   - flake8
#   - pytest
#   - pytest-cov
#   - pip
#   - pip:
#     - fastai>=2.7.0
#     - grad-cam>=1.4.0